#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/sm6115-common

PRODUCT_COPY_FILES += \
    vendor/samsung/sm6115-common/proprietary/recovery/root/vendor/firmware/Himax_firmware_djn_jdi.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/Himax_firmware_djn_jdi.bin \
    vendor/samsung/sm6115-common/proprietary/recovery/root/vendor/firmware/Himax_firmware_hlt_auo.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/Himax_firmware_hlt_auo.bin \
    vendor/samsung/sm6115-common/proprietary/recovery/root/vendor/firmware/Himax_firmware_inx_fhd.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/Himax_firmware_inx_fhd.bin \
    vendor/samsung/sm6115-common/proprietary/recovery/root/vendor/firmware/Himax_firmware_lide_hsd.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/Himax_firmware_lide_hsd.bin \
    vendor/samsung/sm6115-common/proprietary/recovery/root/vendor/firmware/Himax_firmware_tianma_tianma.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/Himax_firmware_tianma_tianma.bin \
    vendor/samsung/sm6115-common/proprietary/recovery/root/vendor/firmware/Himax_firmware_txd_auo.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/Himax_firmware_txd_auo.bin \
    vendor/samsung/sm6115-common/proprietary/recovery/root/vendor/firmware/Himax_firmware_txd_auo_al.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/Himax_firmware_txd_auo_al.bin \
    vendor/samsung/sm6115-common/proprietary/recovery/root/vendor/firmware/Himax_firmware_txd_inx.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/Himax_firmware_txd_inx.bin \
    vendor/samsung/sm6115-common/proprietary/recovery/root/vendor/firmware/focal_ts_fw_lide_hsd.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/focal_ts_fw_lide_hsd.bin \
    vendor/samsung/sm6115-common/proprietary/recovery/root/vendor/firmware/focal_ts_fw_tianma_tianma.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/focal_ts_fw_tianma_tianma.bin \
    vendor/samsung/sm6115-common/proprietary/recovery/root/vendor/firmware/focal_ts_mp_lide_hsd.ini:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/focal_ts_mp_lide_hsd.ini \
    vendor/samsung/sm6115-common/proprietary/recovery/root/vendor/firmware/focal_ts_mp_tianma_tianma.ini:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/focal_ts_mp_tianma_tianma.ini \
    vendor/samsung/sm6115-common/proprietary/recovery/root/vendor/firmware/focaltech_ts_fw_lide.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/focaltech_ts_fw_lide.bin \
    vendor/samsung/sm6115-common/proprietary/recovery/root/vendor/firmware/novatek_ts_fw_hlt_auo.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_fw_hlt_auo.bin \
    vendor/samsung/sm6115-common/proprietary/recovery/root/vendor/firmware/novatek_ts_fw_lce_panda.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_fw_lce_panda.bin \
    vendor/samsung/sm6115-common/proprietary/recovery/root/vendor/firmware/novatek_ts_fw_lide_hsd.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_fw_lide_hsd.bin \
    vendor/samsung/sm6115-common/proprietary/recovery/root/vendor/firmware/novatek_ts_fw_txd_inx.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_fw_txd_inx.bin \
    vendor/samsung/sm6115-common/proprietary/recovery/root/vendor/firmware/novatek_ts_mp_hlt_auo.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_mp_hlt_auo.bin \
    vendor/samsung/sm6115-common/proprietary/recovery/root/vendor/firmware/novatek_ts_mp_lce_panda.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_mp_lce_panda.bin \
    vendor/samsung/sm6115-common/proprietary/recovery/root/vendor/firmware/novatek_ts_mp_lide_hsd.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_mp_lide_hsd.bin \
    vendor/samsung/sm6115-common/proprietary/recovery/root/vendor/firmware/novatek_ts_mp_txd_inx.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_mp_txd_inx.bin \
    vendor/samsung/sm6115-common/proprietary/system_ext/etc/permissions/audiosphere.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/audiosphere.xml \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/IDP/IDP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/IDP/IDP_Bluetooth_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/IDP/IDP_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/IDP/IDP_General_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/IDP/IDP_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/IDP/IDP_Global_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/IDP/IDP_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/IDP/IDP_Handset_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/IDP/IDP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/IDP/IDP_Hdmi_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/IDP/IDP_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/IDP/IDP_Headset_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/IDP/IDP_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/IDP/IDP_Speaker_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/IDP/IDP_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/IDP/IDP_workspaceFile.qwsp \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD/QRD_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD/QRD_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD/QRD_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD/QRD_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD/QRD_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_workspaceFile.qwsp \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_chc/QRD_chc_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_chc/QRD_chc_Bluetooth_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_chc/QRD_chc_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_chc/QRD_chc_General_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_chc/QRD_chc_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_chc/QRD_chc_Global_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_chc/QRD_chc_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_chc/QRD_chc_Handset_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_chc/QRD_chc_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_chc/QRD_chc_Hdmi_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_chc/QRD_chc_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_chc/QRD_chc_Headset_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_chc/QRD_chc_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_chc/QRD_chc_Speaker_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_chc/QRD_chc_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_chc/QRD_chc_workspaceFile.qwsp \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_koo/QRD_koo_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_koo/QRD_koo_Bluetooth_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_koo/QRD_koo_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_koo/QRD_koo_General_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_koo/QRD_koo_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_koo/QRD_koo_Global_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_koo/QRD_koo_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_koo/QRD_koo_Handset_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_koo/QRD_koo_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_koo/QRD_koo_Hdmi_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_koo/QRD_koo_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_koo/QRD_koo_Headset_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_koo/QRD_koo_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_koo/QRD_koo_Speaker_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_koo/QRD_koo_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_koo/QRD_koo_workspaceFile.qwsp \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_mea/QRD_mea_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_mea/QRD_mea_Bluetooth_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_mea/QRD_mea_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_mea/QRD_mea_General_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_mea/QRD_mea_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_mea/QRD_mea_Global_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_mea/QRD_mea_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_mea/QRD_mea_Handset_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_mea/QRD_mea_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_mea/QRD_mea_Hdmi_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_mea/QRD_mea_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_mea/QRD_mea_Headset_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_mea/QRD_mea_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_mea/QRD_mea_Speaker_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_mea/QRD_mea_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_mea/QRD_mea_workspaceFile.qwsp \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_sea/QRD_sea_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_sea/QRD_sea_Bluetooth_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_sea/QRD_sea_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_sea/QRD_sea_General_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_sea/QRD_sea_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_sea/QRD_sea_Global_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_sea/QRD_sea_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_sea/QRD_sea_Handset_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_sea/QRD_sea_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_sea/QRD_sea_Hdmi_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_sea/QRD_sea_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_sea/QRD_sea_Headset_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_sea/QRD_sea_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_sea/QRD_sea_Speaker_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_sea/QRD_sea_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_sea/QRD_sea_workspaceFile.qwsp \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_swa/QRD_swa_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_swa/QRD_swa_Bluetooth_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_swa/QRD_swa_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_swa/QRD_swa_General_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_swa/QRD_swa_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_swa/QRD_swa_Global_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_swa/QRD_swa_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_swa/QRD_swa_Handset_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_swa/QRD_swa_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_swa/QRD_swa_Hdmi_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_swa/QRD_swa_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_swa/QRD_swa_Headset_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_swa/QRD_swa_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_swa/QRD_swa_Speaker_cal.acdb \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/acdbdata/QRD_swa/QRD_swa_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD_swa/QRD_swa_workspaceFile.qwsp \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/camera/camxoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camxoverridesettings.txt \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/charger_fstab.qti:$(TARGET_COPY_OUT_VENDOR)/etc/charger_fstab.qti \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/flp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/flp.conf \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/gnss_antenna_info.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gnss_antenna_info.conf \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/gpfspath_oem_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gpfspath_oem_config.xml \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/gps.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gps.conf \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/android.hardware.drm@1.3-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.3-service.widevine.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/android.hardware.gnss@2.1-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss@2.1-service-qti.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/android.hardware.neuralnetworks@1.3-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@1.3-service-qti.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/init.qti.qcv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.qcv.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/init.vendor.sensors.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.sensors.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/init_thermal-engine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_thermal-engine.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/ipa_fws.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipa_fws.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/qdcmss.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qdcmss.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/qseecomd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qseecomd.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/ssgtzd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ssgtzd.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/vaultkeeper_common.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vaultkeeper_common.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/vendor.display.color@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.display.color@1.0-service.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/vendor.qti.adsprpc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.adsprpc-service.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/vendor.qti.cdsprpc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.cdsprpc-service.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/vendor.qti.hardware.charger_monitor@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.charger_monitor@1.0-service.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/vendor.qti.hardware.dsp@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.dsp@1.0-service.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/vendor.qti.hardware.perf@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.perf@2.2-service.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/vendor.qti.hardware.sensorscalibrate@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.sensorscalibrate@1.0-service.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/vendor.samsung.hardware.thermal@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.thermal@1.0-service.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/vendor.sensors.qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.qti.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/vendor.sensors.sscrpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.sscrpcd.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/wifi_qcom.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi_qcom.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/init/wifi_sec.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wifi_sec.rc \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/izat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/izat.conf \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/lm/AdaptLaunchFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/AdaptLaunchFeature.xml \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/lowi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/lowi.conf \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/msm_irqbalance.conf:$(TARGET_COPY_OUT_VENDOR)/etc/msm_irqbalance.conf \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/perf/commonresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonresourceconfigs.xml \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/perf/commonsysnodesconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonsysnodesconfigs.xml \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/perf/perfboostsconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfboostsconfig.xml \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/perf/perfconfigstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfconfigstore.xml \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/perf/targetconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetconfig.xml \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/perf/targetresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetresourceconfigs.xml \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/permissions/vendor-qti-hardware-sensorscalibrate.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/vendor-qti-hardware-sensorscalibrate.xml \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/powerhint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/powerhint.xml \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sap.conf \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sec_config:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/seccomp_policy/vendor.qti.hardware.dsp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/vendor.qti.hardware.dsp.policy \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/P85943AA2_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/P85943AA2_ak991x_0.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/P85943AA2_bmi26x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/P85943AA2_bmi26x_0.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/P85943AA2_bu52053nvx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/P85943AA2_bu52053nvx_0.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/P85943AA2_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/P85943AA2_default_sensors.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/P85943AA2_hx90xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/P85943AA2_hx90xx_0.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/P85943AA2_icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/P85943AA2_icm4x6xx_0.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/P85943AA2_mmc5603x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/P85943AA2_mmc5603x_0.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/P85943AA2_st480ms_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/P85943AA2_st480ms_0.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/P85943AA2_stk3x2x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/P85943AA2_stk3x2x_0.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/P85943AA2_stk3x2xb_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/P85943AA2_stk3x2xb_0.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/P85943AA2_sx933x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/P85943AA2_sx933x_0.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/p85943AA2_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/p85943AA2_dynamic_sensors.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/p85943AA2_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/p85943AA2_power_0.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aont.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_basic_gestures.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_bring_to_ear.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_ccd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_ccd_v2_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v2_walk.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_ccd_v3_1_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_1_walk.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_ccd_v3_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_walk.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_device_orient.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_direct_channel.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_direct_channel.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_facing.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_fmv_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv_legacy.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_geomag_rv.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_heart_rate.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_heart_rate.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal_legacy.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_multishake.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_disabled.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/config/sns_wrist_pedo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_wrist_pedo.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/descriptor.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/descriptor.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/nanopb.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/nanopb.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_accel.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_accel.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_accel_cal.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_accel_cal.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_activity_recognition.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_activity_recognition.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_ambient_light.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_ambient_light.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_ambient_temperature.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_ambient_temperature.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_amd.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_amd.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_aont.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_aont.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_basic_gestures.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_basic_gestures.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_bring_to_ear.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_bring_to_ear.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_cal.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_cal.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_client.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_client.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_cmc.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_cmc.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_da_test.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_da_test.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_device_mode.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_device_mode.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_device_orient.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_device_orient.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_diag.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_diag.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_diag_sensor.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_diag_sensor.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_direct_channel.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_direct_channel.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_dpc.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_dpc.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_ext_svc.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_ext_svc.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_facing.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_facing.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_fmv.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_fmv.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_formatter.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_formatter.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_fw.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_fw.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_game_rv.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_game_rv.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_geomag_rv.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_geomag_rv.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_gravity.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_gravity.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_gyro.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_gyro.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_gyro_cal.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_gyro_cal.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_gyro_rot_matrix.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_gyro_rot_matrix.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_hall.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_hall.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_heart_beat.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_heart_beat.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_heart_rate.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_heart_rate.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_hinge_angle.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_hinge_angle.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_humidity.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_humidity.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_mag.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_mag.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_mag_cal.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_mag_cal.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_oem1.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_oem1.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_offbody_detect.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_offbody_detect.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_pedometer.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_pedometer.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_pedometer_wrist.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_pedometer_wrist.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_physical_sensor_test.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_physical_sensor_test.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_pose_6dof.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_pose_6dof.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_ppg.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_ppg.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_pressure.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_pressure.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_proximity.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_proximity.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_psmd.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_psmd.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_registry.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_registry.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_resampler.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_resampler.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_rgb.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_rgb.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_rmd.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_rmd.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_rotv.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_rotv.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_sar.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_sar.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_sensor_temperature.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_sensor_temperature.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_sig_motion.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_sig_motion.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_std.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_std.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_std_event_gated_sensor.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_std_event_gated_sensor.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_std_sensor.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_std_sensor.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_std_type.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_std_type.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_step_detect.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_step_detect.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_suid.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_suid.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_thermopile.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_thermopile.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_threshold.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_threshold.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_tilt.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_tilt.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_tilt_to_wake.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_tilt_to_wake.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_ultra_violet.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_ultra_violet.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/proto/sns_wrist_tilt_gesture.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_wrist_tilt_gesture.proto \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/ssg/ta_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/ta_config.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/ssg/tz_whitelist.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/tz_whitelist.json \
    vendor/samsung/sm6115-common/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/Data.msc:$(TARGET_COPY_OUT_VENDOR)/firmware/Data.msc \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/Himax_firmware_djn_jdi.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Himax_firmware_djn_jdi.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/Himax_firmware_hlt_auo.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Himax_firmware_hlt_auo.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/Himax_firmware_inx_fhd.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Himax_firmware_inx_fhd.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/Himax_firmware_lide_hsd.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Himax_firmware_lide_hsd.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/Himax_firmware_tianma_tianma.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Himax_firmware_tianma_tianma.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/Himax_firmware_txd_auo.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Himax_firmware_txd_auo.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/Himax_firmware_txd_auo_al.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Himax_firmware_txd_auo_al.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/Himax_firmware_txd_inx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Himax_firmware_txd_inx.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/a620_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a620_zap.b00 \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/a620_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a620_zap.b01 \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/a620_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a620_zap.b02 \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/a620_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a620_zap.elf \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/a620_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a620_zap.mdt \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/a630_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_sqe.fw \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/a650_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a650_gmu.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/a650_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a650_sqe.fw \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/a650_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a650_zap.b00 \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/a650_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a650_zap.b01 \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/a650_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a650_zap.b02 \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/a650_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a650_zap.elf \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/a650_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a650_zap.mdt \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/a702_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a702_sqe.fw \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/a702_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a702_zap.b00 \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/a702_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a702_zap.b01 \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/a702_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a702_zap.b02 \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/a702_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a702_zap.elf \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/a702_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a702_zap.mdt \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/apbtfw11.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/apbtfw11.tlv \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/apnv11.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/apnv11.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/dax_param.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dax_param.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/focal_ts_fw_lide_hsd.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focal_ts_fw_lide_hsd.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/focal_ts_fw_tianma_tianma.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focal_ts_fw_tianma_tianma.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/focal_ts_mp_lide_hsd.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/focal_ts_mp_lide_hsd.ini \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/focal_ts_mp_tianma_tianma.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/focal_ts_mp_tianma_tianma.ini \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/focaltech_ts_fw_lide.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_ts_fw_lide.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/fs1801.fsm:$(TARGET_COPY_OUT_VENDOR)/firmware/fs1801.fsm \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/hx_criteria_auo.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/hx_criteria_auo.csv \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/hx_criteria_djn.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/hx_criteria_djn.csv \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/hx_criteria_inx.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/hx_criteria_inx.csv \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/hx_criteria_tianma.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/hx_criteria_tianma.csv \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/ipa_fws.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b00 \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/ipa_fws.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b01 \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/ipa_fws.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b02 \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/ipa_fws.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b03 \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/ipa_fws.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b04 \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/ipa_fws.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.elf \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/ipa_fws.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.mdt \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/novatek_ts_fw_hlt_auo.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw_hlt_auo.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/novatek_ts_fw_lce_panda.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw_lce_panda.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/novatek_ts_fw_lide_hsd.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw_lide_hsd.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/novatek_ts_fw_txd_inx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw_txd_inx.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/novatek_ts_mp_hlt_auo.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_mp_hlt_auo.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/novatek_ts_mp_lce_panda.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_mp_lce_panda.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/novatek_ts_mp_lide_hsd.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_mp_lide_hsd.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/novatek_ts_mp_txd_inx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_mp_txd_inx.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/scuba_ipa_fws.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/scuba_ipa_fws.b00 \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/scuba_ipa_fws.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/scuba_ipa_fws.b01 \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/scuba_ipa_fws.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/scuba_ipa_fws.b02 \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/scuba_ipa_fws.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/scuba_ipa_fws.b03 \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/scuba_ipa_fws.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/scuba_ipa_fws.b04 \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/scuba_ipa_fws.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/scuba_ipa_fws.elf \
    vendor/samsung/sm6115-common/proprietary/vendor/firmware/scuba_ipa_fws.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/scuba_ipa_fws.mdt \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.sensormodule.lce_s5k3p9.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.lce_s5k3p9.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.sensormodule.lce_s5k4h7.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.lce_s5k4h7.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.sensormodule.lce_s5k5e9yx04.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.lce_s5k5e9yx04.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.sensormodule.n19_c8490_back_dongci.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.n19_c8490_back_dongci.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.sensormodule.n19_gc5035_front_cxt.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.n19_gc5035_front_cxt.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.sensormodule.n19_gc5035_front_cxt_7e.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.n19_gc5035_front_cxt_7e.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.sensormodule.n19_gc5035_front_qunhui.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.n19_gc5035_front_qunhui.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.sensormodule.n19_gc5035_front_unionimage.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.n19_gc5035_front_unionimage.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.sensormodule.n19_gc8034_back_cxt.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.n19_gc8034_back_cxt.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.sensormodule.n19_hi556_front_shengtai.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.n19_hi556_front_shengtai.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.sensormodule.n19_hi846_back_txd.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.n19_hi846_back_txd.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.sensormodule.n19_s5k4h7yx_back_dongci.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.n19_s5k4h7yx_back_dongci.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.sensormodule.n19_s5k4h7yx_back_helitai.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.n19_s5k4h7yx_back_helitai.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.sensormodule.qti_tpg0.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.qti_tpg0.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.sensormodule.qti_tpg1.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.qti_tpg1.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.sensormodule.qti_tpg2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.qti_tpg2.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.sensormodule.sunny_imx519.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.sunny_imx519.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.sensormodule.truly_imx476.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.truly_imx476.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.agatti_lce_s5k3p9.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.agatti_lce_s5k3p9.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.agatti_lce_s5k4h7.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.agatti_lce_s5k4h7.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.agatti_lce_s5k5e9yx04.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.agatti_lce_s5k5e9yx04.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.agatti_no_mfnr_lce_s5k3p9.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.agatti_no_mfnr_lce_s5k3p9.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.agatti_truly_imx476.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.agatti_truly_imx476.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.default.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.divar_lce_s5k3p9.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.divar_lce_s5k3p9.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.divar_lce_s5k4h7.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.divar_lce_s5k4h7.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.divar_lce_s5k5e9yx04.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.divar_lce_s5k5e9yx04.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.divar_truly_imx476.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.divar_truly_imx476.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.lce_s5k3p9.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.lce_s5k3p9.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.lce_s5k4h7.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.lce_s5k4h7.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.lce_s5k5e9yx04.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.lce_s5k5e9yx04.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.n19_c8490_back_dongci.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.n19_c8490_back_dongci.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.n19_gc5035_front_cxt.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.n19_gc5035_front_cxt.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.n19_gc5035_front_qunhui.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.n19_gc5035_front_qunhui.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.n19_gc5035_front_unionimage.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.n19_gc5035_front_unionimage.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.n19_gc8034_back_cxt.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.n19_gc8034_back_cxt.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.n19_hi556_front_shengtai.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.n19_hi556_front_shengtai.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.n19_hi846_back_txd.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.n19_hi846_back_txd.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.n19_s5k4h7yx_back_dongci.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.n19_s5k4h7yx_back_dongci.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.n19_s5k4h7yx_back_helitai.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.n19_s5k4h7yx_back_helitai.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/com.qti.tuned.truly_imx476.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.truly_imx476.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/samsung/sm6115-common/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin

PRODUCT_PACKAGES += \
    android.hardware.gnss@2.1-impl-qti \
    eglSubDriverAndroid \
    libC2D2 \
    libCB \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libOpenCL \
    libOpenCv.camera.samsung \
    libVkLayer_q3dtools \
    libadreno_utils \
    libaudioalsa \
    libbatching \
    libc2d30_bltlib \
    libcdsprpc \
    libdiag \
    libdiagjni \
    libdsutils \
    libfastcvdsp_stub \
    libfastcvopt \
    libfloatingfeature \
    libgeofencing \
    libgnss \
    libgnsspps \
    libgps.utils \
    libgpudataproducer \
    libgsl \
    libidl \
    libllvm-glnext \
    libllvm-qcom \
    libloc_core \
    libloc_socket \
    liblocation_api \
    libmdmdetect \
    libminkdescriptor \
    libminksocket \
    libmmosal \
    libnative-api \
    libperfconfig \
    libperfgluelayer \
    libperfioctl \
    libq3dtools_adreno \
    libq3dtools_esx \
    libqcbor \
    libqcci_legacy \
    libqdi \
    libqdp \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmi_legacy \
    libqmiservices \
    libqrtr \
    libQSEEComAPI \
    libqti-perfd \
    libqti-perfd-client \
    libqti-util \
    libqti-utils \
    libsecnativefeature \
    libsemnativecarrierfeature \
    libsensorndkbridge \
    libsi \
    libsns_registry_skel \
    libsynergy_loc_api \
    libthermalclient \
    libtime_genoff \
    libtrustedapploader \
    libtzdrmgenprov \
    libwingmetamanager \
    vendor.qti.hardware.dsp@1.0 \
    vendor.qti.memory.pasrmanager@1.0 \
    vendor.qti.memory.pasrmanager@1.1 \
    vendor.samsung.hardware.gnss@2.0 \
    vendor.samsung.hardware.gnss@2.0-impl-sec \
    vulkan.adreno \
    audio.primary.bengal \
    btaudio_offload_if \
    liba2dpoffload \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libadm \
    libadpcmdec \
    libasphere \
    libaudcal \
    libaudio_log_utils \
    libaudioconfigstore \
    libaudioeffectoffload \
    libaudioparsers \
    libbatterylistener \
    libbluetooth_audio_session_qti \
    libbluetooth_audio_session_qti_2_1 \
    libcirrusspkrprot \
    libcomprcapture \
    libexthwplugin \
    libfastcrc \
    libgcs \
    libgcs-calwrapper \
    libgcs-ipc \
    libgcs-osal \
    libhdmiedid \
    libhdmipassthru \
    libhfp \
    libmulawdec \
    libprofileparamstorage \
    libqcbassboost \
    libqcreverb \
    libqcvirt \
    libqtigef \
    libsecaudiocoreutils \
    libsecaudioinfo \
    libshoebox \
    libsndmonitor \
    libspeakercalibration \
    libspkrprot \
    libsurround_3mic_proc \
    libswdap \
    libwvdrmengine \
    libwvhidl \
    vendor.qti.hardware.bluetooth_audio@2.0-impl \
    vendor.qti.hardware.bluetooth_audio@2.1-impl \
    android.hardware.bluetooth@1.0-impl-qti \
    android.hardware.gatekeeper@1.0-impl-qti \
    camera.qcom \
    com.morpho.node.videorefiner \
    com.qti.camx.chiiqutils \
    com.qti.chi.override \
    com.qti.chiusecaseselector \
    com.qti.eeprom.irs2381c_polar \
    com.qti.eeprom.n19_gc8034_back_cxt \
    com.qti.eeprom.truly_cmb433 \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.frameselect \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs \
    com.qti.feature2.hdr \
    com.qti.feature2.memcpy \
    com.qti.feature2.mfsr \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.rt \
    com.qti.feature2.serializer \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    com.qti.flash.lm3644 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.dewarp \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.remosaic \
    com.qti.node.stich \
    com.qti.node.swaidenoiser \
    com.qti.node.swcac \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swmfnr \
    com.qti.node.swregistration \
    com.qti.sensor.imx318 \
    com.qti.sensor.imx334 \
    com.qti.sensor.imx362 \
    com.qti.sensor.imx376 \
    com.qti.sensor.imx386 \
    com.qti.sensor.imx476 \
    com.qti.sensor.imx481 \
    com.qti.sensor.imx519 \
    com.qti.sensor.imx576 \
    com.qti.sensor.imx577 \
    com.qti.sensor.imx586 \
    com.qti.sensor.max7366_6dof \
    com.qti.sensor.max7366_eyetrack \
    com.qti.sensor.max7366_ov6211 \
    com.qti.sensor.max7366_ov9282 \
    com.qti.sensor.n19_c8490_back_dongci \
    com.qti.sensor.n19_gc5035_front_cxt \
    com.qti.sensor.n19_gc5035_front_qunhui \
    com.qti.sensor.n19_gc5035_front_unionimage \
    com.qti.sensor.n19_gc8034_back_cxt \
    com.qti.sensor.n19_hi556_front_shengtai \
    com.qti.sensor.n19_hi846_back_txd \
    com.qti.sensor.n19_s5k4h7yx_back_dongci \
    com.qti.sensor.n19_s5k4h7yx_back_helitai \
    com.qti.sensor.ov12a10 \
    com.qti.sensor.ov12a10_front \
    com.qti.sensor.ov13855 \
    com.qti.sensor.ov13880 \
    com.qti.sensor.ov6211_master \
    com.qti.sensor.ov6211_slave \
    com.qti.sensor.ov7251 \
    com.qti.sensor.ov8856 \
    com.qti.sensor.ov8856_master \
    com.qti.sensor.ov8856_slave \
    com.qti.sensor.ov9282_master \
    com.qti.sensor.ov9282_slave \
    com.qti.sensor.s5k2l7 \
    com.qti.sensor.s5k2x5sp \
    com.qti.sensor.s5k3m5 \
    com.qti.sensor.s5k3p9 \
    com.qti.sensor.s5k4h7 \
    com.qti.sensor.s5k5e9yu05 \
    com.qti.sensor.s5k5e9yx04 \
    com.qti.stats.aec \
    com.qti.stats.aecwrapper \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.tracker \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    com.qualcomm.qti.ant@1.0 \
    com.qualcomm.qti.ant@1.0-impl \
    com.qualcomm.qti.ant@1.0_vendor \
    gatekeeper.mdfpp \
    android.hardware.gatekeeper@1.0-impl \
    libGPTEE_vendor \
    libGPreqcancel \
    libGPreqcancel_svc \
    libhdcpsrm \
    libSecureUILib \
    libStDrvInt \
    libadaptlaunch \
    libadsp_default_listener \
    libadsprpc \
    libaidenoiser \
    libbitmlengine \
    libbtnv \
    libcamera2ndk_vendor \
    libcamera_nn_stub \
    libcamerapostproc \
    libcamxexternalformatutils \
    libcamxfacialfeatures \
    libcamxfdalgo \
    libcamxfdengine \
    libcamxifestriping \
    libcamximageformatutils \
    libcamxncs \
    libcamxstatscore \
    libcamxswispiqmodule \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libcapiv2svacnn \
    libcapiv2svarnn \
    libcapiv2vop \
    libcdfw \
    libcdfw_remote_api \
    libcdsp_default_listener \
    libchilog \
    libcom.qti.chinodeutils \
    libconfigdb \
    libcpion \
    libdataitems \
    libdisp-aba \
    libdisplayqos \
    libdisplayskuutils \
    libdpps \
    libdrmfs \
    libdrmtime \
    libdsi_netctrl \
    libdsms_vendor \
    libgrdm \
    libhdr_tm \
    libhexagon_nn_stub \
    libhypervintf \
    libipebpsstriping \
    libizat_client_api \
    libizat_core \
    libjpege \
    libkeymaster_helper \
    libkeymasterdeviceutils \
    libkeymasterutils \
    liblbs_core \
    liblearningmodule \
    liblmutils-ns \
    libloadalgo_stub \
    libloc_api_v02 \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    libmctfengine_stub \
    libmdsprpc \
    libmeters \
    libmeters-ns \
    libmmcamera_cac3 \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_lscv35 \
    libmmcamera_mfnr \
    libmmcamera_mfnr_t4 \
    libmorpho_video_refiner \
    libnetmgr \
    libnetmgr_common \
    liboemcrypto \
    libofflinelog \
    libopencv \
    libopestriping \
    libops \
    libpadm \
    libpdmapper \
    libperipheral_client \
    libqcc_file_agent \
    libqcmaputils \
    libqdma_file_agent \
    libqisl \
    libqseed3 \
    libqservice \
    libqsocket \
    libqti-iopd \
    libqti-iopd-client \
    libqtikeymaster4 \
    libreffeature \
    librpmb \
    libsavscmn \
    libscveCommon \
    libscveCommon_stub \
    libscveObjectSegmentation \
    libscveObjectSegmentation_stub \
    libscveObjectTracker \
    libscveObjectTracker_stub \
    libsdm-color \
    libsdm-colormgr-algo \
    libsdm-diag \
    libsdm-disp-vndapis \
    libsdmextension \
    libsdsprpc \
    libsecureui \
    libsecureui_svcsock \
    libsensorcal \
    libsensorslog \
    libskeymaster4device \
    libsns_device_mode_stub \
    libsns_fastRPC_util \
    libsns_low_lat_stream_stub \
    libsnsapi \
    libsnsdiaglog \
    libsoc_helper \
    libssc \
    libssc_default_listener \
    libssd \
    libstork_shared \
    libswregistrationalgo \
    libsysmon_cdsp_skel \
    libtinyxml2_1 \
    libvkmanager_vendor \
    libvkservice \
    libxml \
    libxtadapter \
    sensors.ssc \
    unnhal-acc-adreno \
    unnhal-acc-common \
    unnhal-acc-hvx \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.color@1.3 \
    vendor.display.color@1.4 \
    vendor.display.color@1.5 \
    vendor.display.postproc@1.0 \
    vendor.qti.gnss@1.0 \
    vendor.qti.gnss@1.1 \
    vendor.qti.gnss@1.2 \
    vendor.qti.gnss@2.0 \
    vendor.qti.gnss@2.1 \
    vendor.qti.gnss@3.0 \
    vendor.qti.gnss@4.0 \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.1 \
    vendor.qti.hardware.bluetooth_sar@1.1-impl \
    vendor.qti.hardware.btconfigstore@1.0-impl \
    vendor.qti.hardware.btconfigstore@2.0-impl \
    vendor.qti.hardware.camera.postproc@1.0-service-impl \
    vendor.qti.hardware.capabilityconfigstore@1.0-impl \
    vendor.qti.hardware.cvp@1.0 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.iop@2.0 \
    vendor.qti.hardware.qccsyshal@1.0 \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.qseecom@1.0-impl \
    vendor.qti.hardware.scve.objecttracker@1.0 \
    vendor.qti.hardware.scve.panorama@1.0 \
    vendor.qti.hardware.sensorscalibrate@1.0 \
    vendor.qti.hardware.sensorscalibrate@1.0-impl \
    vendor.qti.hardware.tui_comm@1.0 \
    vendor.qti.hardware.vpp@1.1 \
    vendor.qti.hardware.vpp@1.2 \
    vendor.samsung.frameworks.security.dsms@1.0 \
    vendor.samsung.hardware.hyper-V2-ndk_platform \
    vendor.samsung.hardware.security.vaultkeeper@2.0 \
    vendor.samsung.hardware.thermal@1.0 \
    vendor_lib_rfsa_adsp_libadsp_jpege_skel_so \
    vendor_lib_rfsa_adsp_libapps_mem_heap_so \
    vendor_lib_rfsa_adsp_libbitml_nsp_skel_so \
    vendor_lib_rfsa_adsp_libcamera_nn_skel_so \
    vendor_lib_rfsa_adsp_libdspCV_skel_so \
    vendor_lib_rfsa_adsp_libdsp_streamer_binning_so \
    vendor_lib_rfsa_adsp_libfastcvadsp_so \
    vendor_lib_rfsa_adsp_libfastcvdsp_skel_so \
    vendor_lib_rfsa_adsp_libhexagon_nn_skel_so \
    vendor_lib_rfsa_adsp_libmctfengine_skel_so \
    vendor_lib_rfsa_adsp_libscveObjectSegmentation_skel_so \
    vendor_lib_rfsa_adsp_libscveT2T_skel_so \
    vendor_lib_rfsa_adsp_libsns_device_mode_skel_so \
    vendor_lib_rfsa_adsp_libsns_low_lat_stream_skel_so \
    TimeService \
    audiosphere \
    android.hardware.gnss@2.1-service-qti.xml \
    manifest_android.hardware.drm@1.3-service.widevine.xml \
    vaultkeeper_manifest.xml \
    vendor.samsung.hardware.thermal@1.0-manifest.xml \
    adsprpcd \
    cdsprpcd \
    chifeature2test \
    chiofflinepostproctest \
    cnss-daemon \
    dspservice \
    hvdcp_opti \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.drm@1.3-service.widevine \
    android.hardware.gatekeeper@1.0-service \
    android.hardware.keymaster@4.0-service \
    android.hardware.neuralnetworks@1.3-service-qti \
    android.hardware.gnss@2.1-service-qti \
    macloader \
    vendor.display.color@1.0-service \
    vendor.qti.hardware.capabilityconfigstore@1.0-service \
    vendor.qti.hardware.perf@2.2-service \
    vendor.qti.hardware.qseecom@1.0-service \
    vendor.qti.hardware.sensorscalibrate@1.0-service \
    vendor.qti.hardware.tui_comm@1.0-service-qti \
    vendor.samsung.hardware.thermal@1.0-service \
    irsc_util \
    loc_launcher \
    lowi-server \
    mlid \
    msm_irqbalance \
    pd-mapper \
    pm-proxy \
    pm-service \
    ppd \
    qdcmss \
    qrtr-ns \
    qseecomd \
    rmt_storage \
    sensors.qti \
    sscrpcd \
    ssgqmigd \
    ssgtzd \
    ssr_diag \
    ssr_setup \
    subsystem_ramdump \
    tftp_server \
    thermal-engine \
    time_daemon \
    vaultkeeperd \
    vendor.samsung.hardware.security.vaultkeeper@2.0-service \
    wt_rpmb_status \
    xtra-daemon

PRODUCT_PACKAGES += \
    vendor_lib_libEGL_adreno_so \
    vendor_lib_libGLESv2_adreno_so \
    vendor_lib_libq3dtools_adreno_so \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so \
    vendor_lib64_libq3dtools_adreno_so
